# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9564e31930a64cff69749d964a92c0dc95325293ebaf5dda3b3247ec2d6d344091734db300367e1237a0f2e999020dad9a33930a500d79cccb7e44b61819e0d

test:
  secret_key_base: e451a924b12fbbeb8abb18a5a852c73088a4c2517992dcdb5069c4145a214b03abc5fae6cf6d6c62cc8723b9966f12e31bb5761bc301a33e08d23b39bacfb590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
